version: "1"

metadata:
  template: false

steps:
  - name: build
    image: eclipse-temurin:25-jdk-jammy
    pull: always
    commands:
      - ./gradlew --no-daemon clean assemble

  - name: unit-test
    image: eclipse-temurin:25-jdk-jammy
    commands:
      - ./gradlew --no-daemon test

  - name: integration-test
    image: docker.io/library/docker:29-dind
    environment:
      DOCKER_HOST: tcp://localhost:2375
    commands:
      - apk add --no-cache openjdk21
      - ./gradlew --no-daemon integrationTest

  - name: docker-build
    image: docker.io/library/docker:29-cli
    environment:
      DOCKER_HOST: tcp://localhost:2375
    commands:
      - docker build -t sca-demo:${VELA_BUILD_COMMIT:0:7} .

services:
  - name: docker
    image: docker.io/library/docker:29-dind
